# Challenge Data IQ - Data Science

In [13]:
import numpy as np
from sklearn.svm import LinearSVC
from sklearn.datasets import load_iris
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

In [15]:
x, y = make_classification(n_samples=5000, n_features=10,
                          n_classes=3,
                          n_clusters_per_class=1)

print(x[0:5])
print(y[0:5])

[[ 1.1543221   0.49430272  0.04778212  1.3969018   0.11045944 -0.1973946
   1.13986714 -0.24050694 -1.72352242  0.14590344]
 [-1.07965328 -0.1552757   1.60961788  1.3455858   0.64525314  0.05542002
   0.36220702  1.6037825   1.67415747 -0.29052177]
 [-0.33037018 -0.5153073   1.70812882  1.43350335 -1.02677609  1.45007061
   0.71913712  1.02196124 -0.18798767 -0.14825039]
 [-0.83252067 -0.8416407   0.51592067  0.65138293 -0.67089939  0.35123962
   1.52506707  1.03589336  0.47190688 -0.20158792]
 [ 1.69723988  0.47457902  0.3719596   0.43455632 -0.68741455  1.87608484
  -1.51721439 -1.19552457 -0.20594426  0.30859181]]
[2 1 1 1 2]


In [27]:
xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size=.15)

In [29]:
lsvc=LinearSVC(dual=False)
print(lsvc)

LinearSVC(dual=False)


In [33]:
lsvc.fit(xtrain, ytrain)
score=lsvc.score(xtrain, ytrain)
print("Score: ", score)

Score:  0.9294117647058824


In [35]:
cv_score=cross_val_score(lsvc, xtrain, ytrain, cv=10)
print("CV average score: ", cv_score.mean())

CV average score:  0.9277647058823527


In [39]:
ypred=lsvc.predict(xtest)
cm=confusion_matrix(ytest, ypred)
print(cm)

[[238   1   4]
 [  1 234  22]
 [ 12  19 219]]


In [41]:
cr=classification_report(ytest, ypred)
print(cr)

              precision    recall  f1-score   support

           0       0.95      0.98      0.96       243
           1       0.92      0.91      0.92       257
           2       0.89      0.88      0.88       250

    accuracy                           0.92       750
   macro avg       0.92      0.92      0.92       750
weighted avg       0.92      0.92      0.92       750



In [45]:
print("Iris dataset classification with LinearSVC")
iris=load_iris()
x, y = iris.data, iris.target
xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size =.15)

Iris dataset classification with LinearSVC


In [47]:
lsvc=LinearSVC(dual=False)
print(lsvc)

lsvc.fit(xtrain, ytrain)
score = lsvc.score(xtrain, ytrain)
print("Score: ", score)

cv_scores = cross_val_score(lsvc, xtrain, ytrain, cv=10)
print("CV average score: ", cv_scores.mean())

ypred = lsvc.predict(xtest)

cm = confusion_matrix(ytest, ypred)
print(cm)

cr = classification_report(ytest, ypred)
print(cr)

LinearSVC(dual=False)
Score:  0.9763779527559056
CV average score:  0.9525641025641025
[[8 0 0]
 [0 7 0]
 [0 0 8]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         8
           1       1.00      1.00      1.00         7
           2       1.00      1.00      1.00         8

    accuracy                           1.00        23
   macro avg       1.00      1.00      1.00        23
weighted avg       1.00      1.00      1.00        23

